# General Discussion

We have so far delved into detailed reports of work studying echolocation in groups, and various methodological contributions to the field. In this section I will summarise some broad points of interest, and end with my vision for the future of the field. 

## The 'cocktail party nightmare': a hyperbolic term
In their influential review over a decade ago @ulanovsky2008a coined the term 'cocktail party nightmare' to describe the sensory challenge echolocating bats face in groups. How do individual bats manage to detect their own echoes over the deafening calls of neighbours, how to recognise one's own echoes from the constant stream of others' echoes and calls? In comparison to the cocktail party problems that humans (and perhaps other animals) face, the stakes of not detecting an echo seemed high (collision with obstacles), and the emitted sound levels definitely are much higher. The escalation from *problem* to *nightmare* aptly describes the perceived seriousness of group echolocation. Studies since then revealed a variety of responses that echolocators show in their call behaviour to playbacks, and in group flights. Bats were studied as 'emitters' of signals, but understudied as 'receivers'. 

To understand bats as receivers in group echolocation, one must the quantify the extent to which echo detection suffers in groups. The next step is to quantify how much the exhibited call alterations improve echo detection. Using a computational model that recreated the biology, acoustics and geometry of bat groups in great detail I quantified the 'cocktail party nightmare' in great detail in Chapter \@ref(cpnchapter) for FM bats. The results of the model show that when in small groups (<10bats), echo detection is unaffected. All  available echoes are detected regularly each time a call is emitted, and all neighbours spread around the focal bat can be detected  too. With increasing group sizes ($\\geq$30) however, the problem of masking begins to play a progressively stronger role. Already at group sizes of a 100 bats, a focal bat in the middle of the group can only detect at most one neighbour per call emission, and that too only every third call emission. The neighbour that is detected occasionally is the nearest neighbour located in the front of the emitting bat. The high density of intense calls and other bats' echoes means that two of three call emissions will result in the returning echo being masked. At much larger group sizes of 200 bats, the probability of hearing an echo decreases drastically to almost zero. 

I show in \@ref(cpnchapter) that the sensory inputs individuals have while exhibiting collective motion in active sensing groups is qualitatively and quantitatively different from passive sensing visual groups. Despite occlusions, visually-dominant individuals can detect at least their nearest neighbours. My results showed that in large groups, echolocating bats may not even be able to detect their nearest neighbours every time they call. 
If bats in large groups can only detect their nearest neighbour in front of them occasionally, how can groups show collective movements like milling using echolocation? @bode2011a provide an answer with their 'limited interactions' model. @bode2011a show that collective movement emerges even when individuals asynchronously update their own positions with reference to just one neighbour. My model showed that despite the severity of masking in groups, echo detection occurs at large group sizes of a 100 bats. The model however implemented a simple auditory model of echo detection - that did not include dynamic information processing (integration over multiple echoes), temporal gating or attentional processes.  The results from the model are thus lower bound estimates of what a real echolocator may experience, and questions the severity of the problem that bats may experience in groups. In the light of results from my model,  I now wonder whether the cocktail party is more of a 'challenge' than a nightmare for bats in groups?

## Free-flying bats do not show echolocation changes in groups
The experimental study of group echolocation has been driven by the discovery of echolocation responses to the presence of conspecifics or experimental playbacks. Most of these studies have occured in flightroom settings with low duty-cycle FM bats, that emit short calls with long silences in between. In contrast, high duty-cycle CF-FM bats, that emit longer calls with shorter silences in between have remain heavily understudied, despite the fact that the higher duty-cycle makes call-echo overlaps in groups much more likely. One reason perhaps for the lack of investigation in CF-FM bats is the difficulty in analysing audio with call overlaps itself. Moreover, even existing studies themselves had only performed limited quantification of echolocation parameters.

In Chapter \@ref(hbcchapter), I set out to investigate the echolocation of CF-FM bat groups in a natural cave. Using audio and video to record bats in the cave1, I was able to characterise echolocation with respect to group size. To analyse echolocation I used two independent methods to analyse the calls, one included the analysis of individual calls across group size, and the other involved analysing small windows of echolocation sequences. I developed a technique (see Chapter \@ref(itsfmchapter) to reliably segment and measure CF-FM call components,  while the 'window'-based methodology is to my knowledge the first attempt at analysing echolocation in CF-FM groups. I also developed simulations to generate predictions for the expected variation in CF frequencies in bat groups that show no special response to each other. 

The CF-FM bats in our study did not show major changes in their echolocation across group size, and matched predictions from simulations. This lack of response was in contrast to one comparable study, which found strong alterations in call parameters in just pairs of bats. The CF-FM bats in our cave site were in fact seen to fly in groups of upto four at a time, and still did not seem to show any alterations. Bats have short and long-term spatial memory of their surroundings, and are therefore likely to withstand occasional deteriorations in echo reception in groups. Individuals flying in familiar environments may thus not show any obvious alterations in their call behaviour. Our negative result highlights the importance of field studies in group echolocation, and adds 'no response' to the variety of responses shown by bats in groups. 

## *Ushichka*: a model dataset for group active sensing
Continuing in the same field site of Orlova Chuka, but in FM bats, I continue highlighting the importance of field studies. In Chapter \@ref(ushichkachapter) I report my contribution to pushing the frontiers in the study of experimental group echolocation. Group echolocation in the field has been studied either in small groups (2-3 bats), or solely with audio or video. Animals in groups interact with each other, while also responding to the presence of their physical surroundings - like the trees, rocks or walls of a cave. Studies to date have ignored the physical environment, and only been centred on the bats themselves. Data on the simultaneous echolocation and flight behaviours of bats placed in their natural context is lacking. Having such multi-modal data provides exciting insights into the sensory inputs individuals receive, and the motor outputs they perform as a result. 

*Ushichka* is a multi-channel, multi-sensor dataset I collected of FM bats flying in a cave over the course of 14 nights. Using synchronised microphone and camera arrays placed unobtrusively in the cave, I was able to collect echolocation and flight behaviour of bats flying in a variety of naturally occuring group sizes of 1-30 bats at a time. A LiDAR scan of the same recording volume captures the physical context to the observed flight and echolocation behaviour. The many microphones in the acoustic array help in reducing the effect of call overlaps in group echolocation, while the three thermal cameras alleviate the problem of occlusion in multi-body tracking. A inconspicuous approach to acoustic tracking was implemented to reduce the recording of artifactual inspection behaviours. A new approach to inconspicuous microphone arrays in the field was also implemented in *Ushichka*. Microphones were placed freely in the cave, and their positions were estimated automatically through common playbacks as described in Chapter \@ref(sfscotdoa). 

The trajectory and call data from *Ushichka* will allow us to recreate the dynamic sensory inputs of each individual in a group. The position and call timings of individuals can be used in simulations of sound propagation to reconstruct the echo and call arrival times from neighbours, and cave surfaces. While Chapter \@ref(cpnchapter) recreated the sensory inputs of a bat in a group *in silica*, *Ushichka* provides us access to the sensory inputs of bats in a group *in caverna*!. Having reconstructed the sensory inputs of bats in a group, we can then understand the sensorimotor heuristics that govern their collective motion. The collective motion and echolocation of bat groups has only been quantified in the impressive emergence behaviours of *T. brasiliensis* to date [@TOCOMPLETETHERIAULT]. The *T.brasiliensis* studies provide a series of findings that remain unreconciled. Bats emit extremely long calls ($\\geq$6ms) in these dense emergences [@TOCOMPLETEGILLAM], despite flying somewhat close to their neighbours  (~0.5m inter-neighbour distance) [@TOCOMPLETETHERIAULT]. This close-distance flight with long duration calls means their own emitted calls will mask returning echoes. *T. brasiliensis* emergences occur around sunset - to what extent is echolocation really being used by animals in these groups? *Ushichka* provides a 'cleaner' dataset into how echolocation is used in bat groups flying under pitch-black conditions of a cave system. *T. brasiliensis* emergences are indeed a wonder of nature, though I think we are still technologically limited in our ability to analyse the high call densities and call overlap in the audio. I believe the call densities in  *Ushichka* on the other hand lie in the Goldilocks zone of today's technology - we are neither too far from its capabilities, nor too easily handled by regular routines. *Ushichka* promises to generate many novel insights in the fields of active sensing, collective behaviour - and serve as a test bed for many methodological advances in bioacoustics and tracking of animals in the field.

## Lowering the logistical and technical barriers to group echolocation
In Chapters \@ref(sfscotdoa),\@ref(tacostchapter) and \@ref(itsfmchapter) I presented a series of methods that promote the accuracy, automation, and ease with which group echolocation can be studied.

An echolocation call is the emitted probe of energy, which then typically creates a multitude of echoes from each of the objects it encounters. A bat's behavioural state can be inferred by quantifying its call parameters (eg. short, high-bandwidth calls while landing, long calls in the open). Studies to date have relied on manual measurements or in-house scripts to analyse calls - both methods do not lend themselves to public scrutiny or reproducibility of results. I developed and described a series of automated methods to analysis individual call components in the ```itsfm``` package. The ```itsfm``` package moves the field of CF-FM call quantification forward by introducing the use of a new algorithm to segment CF and FM components in CF-FM calls. The new algorithm surpasses the accuracy of a previously described method in its segmentation, and thus leads to better measurements of call parameters. To promote openness, use in the community and user-friendliness, I released ```itsfm``` under an open-source license along with detailed manuals on use-cases.

Studying echolocation in groups of bats necessitates the use of multi-microphone arrays. While designing the array of choice, a variety of questions arise about the number of microphones required, the geometry of microphone positions, type and location of sounds emitted and the resulting accuracy of acoustic tracking. Each of these parameters has an effect on the accuracy with which source positions are tracked. In Chapter \@ref(tacostchapter), I present ```tacost```, a software package designed to create simulated multi-channel audio according to user-defined parameters. While the package does not perform acoustic tracking itself, it provides the necessary simulated input data required to perform acoustic tracking. ```tacost``` may be used pre-experiment to plan and optimise the accuracy of a tracking system, or used post-experiment, to estimate the system's baseline performance. ```tacost``` has also been publicly released with an open-source license and online user-manual.

Multi-microphone arrays are central to the study of echolocation, but are logistically difficult to handle. Typical arrays consist of bulky frames where microphones can be placed in fixed positions. These frames may be the cause of artifactual inspection behaviours from the animals. Working with freely-placed microphones means manually measuring many distances to estimate microphone positions later. The bulkiness and time-intensive nature of current multi-microphone array workflows limit their scaleability and wide deployment. In Chapter \ref(@sfscotdoa), I present the results of a collaboration towards an frame-less, measurement-free approach to acoustic tracking. In the 'Structure-from-Sound' framework used in Chapter \@ref(sfscotdoa), a series of common sounds are first recorded by all microphones. The time-difference-of-arrivals across channels are then used to infer microphone positions. We successfully showed the inference of mic positions to within a few centimetres of the ground-truthed data. In many ways, this new method is the first such application to the field of echolocation, and promises a great reduction in the time spent setting up an array, and the weight of equipment to be carried into the field. The ease and anticipatory joy of such an effortless acoustic tracking workflow can only be described by the words of a senior colleague^[here's to the encouragement of Lasse Jakobsen] who said knowing there were such methods in development was the year's 'Christmas gift'.

## The future of group active sensing research 

### Parametrising group active sensing in bats and other model systems {#parametrising}
The shifting focus of active sensing research from single animals to multi animal groups is understandable as communities of researchers work on developing the increasingly sophisticated technologies required. As with bat echolocation, so it has also been with electric fish. Oilbirds, swiftlets, certain fruit bats and other odontocete echolocators also come to mind. While odontocetes and some fruit bats (so far *Rousettus aegyptiacus* and *R. leschenaulti*) emit very short 'clicks' about tens to hundreds of microseconds long. The probability of an echo being jammed is proportional to the duration of the calls being emitted in a group [@BELEYUR], and in this sense, click-based echolocators are unlikely to suffer problems detecting echoes because of call-echo (or click-echo in this case) overlaps. Short click-based echolocators are still however likely to suffer from all the other related issues that a vertebrate auditory bauplan brings, for example forward and backward masking [@Nachtigall2014], and even perhaps informational masking. Oilbirds and swiflets also emit clicks, but these clicks are much closer in duration to bat echolocation calls, ranging from a one to tens of milliseconds [@brinklov2013echolocation] - making them much more likely to suffer the same kinds of call-echo overlaps that bats do in groups. How click based echolocators manage to recognise their own echoes from the echoes of others is an interesting question that I think is particularly worth pursuing in the future. One strategy echolocating bats may use to recognise their own echoes is the presence of unique vocal signatures or 'voices' [@YOVEL;@MASTERS] in their echolocation calls. Clicks are indeed defined by the apparent absence of spectro-temporal structure [@pye1980echolocation], and their impulse-like structure (much like the clapping of the hand, or a hammer hitting a surface), and given their generally short durrations are so are somewhat unlikely to carry individual-specific signatures. Of course, the absence of a 'voice' in click-based echolocation doesn't preclude the use the other mechanisms that may be common to all echolocators to filter out 'ranging noise', such as temporal gating (using echoes that arrive within an expected time window) or using directional cues to filter out off-target echoes arriving from behind or the sides. 

As receivers, all groups of active sensing echolocators known to date (birds and mammals) are likely to face the common problem of masking. Evidence for the occurence of masking is old, but systematic tests in the context of echolocation have only been done in laryngeal-echolocating bats and odontocetes [@Nachtigall2014]. Most discussions of masking in echolocation have typically been centred around one type of masking, *energetic* masking. Energetic masking is a physiologically driven phenomena where the intensity of louder sounds suppresses the detection of fainter sounds [@YOST]. Another, less discussed type of masking is *informational* masking. Informational masking occurs when signal detection is affected, despite the absence of energetic masking (no temporal or spectral overlap) [@YOST]. For instance, humans experience informational masking when trying to listen to a sentence with unrelated words in between [@TOCOMPLETE]. Unlike energetic masking that occurs primarily at the cochlear level, informational masking is thought to occur due to the interplay of attention and other higher-order phenomena [@TOCOMPLETE]. To my knowledge, there remain no studies of informational masking in echolocating animals - and this presents a yet unexplored facet in the study of individual and group echolocation. Here, I see the scope for the next wave of multi-species phantom echo studies [eg. @SURLYKKe;@SIMMONS;] whose results can be directly used to construct 'masking functions' (sensu @BELEYURGOERLITZ2019). Echolocating bats vary in the continuum of group sizes that they live in [@ECOLOGYOFBATS], and this means the extent of masking that they are likely to experience from conspecifics will also vary. Does this typical group-size based masking have an effect on the actual ability of individuals to detect echoes in noise? It may also be that the robustness of echolocation to noise is more strongly affected by the environmental clutter and reverberance, rather than roosting group size per se.  Studying a wider variety of species will allow us to explore the ecological and evolutionary basis of masking tolerance. 

As emitters, active sensing animals choose how and where to focus their probe's energy [@Fenton2014]. Bats and odontocetes narrow or widen the 'beam shape' of their emissions depending on the behaviour at hand. In essence, individuals choose to 'focus' or 'zoom out' their perceptual field. All beam shape studies I know of have quantified beam shapes and their modulation in solitary animals. A classic result is of bats emitting wide beam-shapes while searching for prey, narrowing onto the prey while approaching, and 'zooming out' just before prey interception [@Fenton2014]. The direction and width of the emitted calls are direct pointers of where an animal is focussing its sensory efforts. The spatial aspects of echolocation in groups remain an area of pure speculation. Do animals emit wide beams to maximise their sensory volume - and pay the costs of mutual interference? Or do they emit narrow beams focussing on the nearest objects around them - at the risk of sudden collision with an object barely out-of sensory range? Call overlaps and small microphone arrays have hindered beam-shape reconstruction in multi-animal groups. At least in click-emitting echolocators, where overlaps may not pose a problem - beam shape modulations in groups represents a fascinating and tractable model system. Large multi-microphone arrays like in the *Ushichka* dataset (or perhaps even more channels may be required!) are the future to study the spatial aspects of signal emission. 

### The three-pronged approach to solve the inverse problem of group active sensing 
The study of biological problems is full of inverse problems. We observe a range of fascinating phenomena, but often are unable to (and perhaps will never be able to!) recreate them under controlled settings. In this respect, biological, geological and cosmological phenomena must be tackled with a synergetic approach involving 1) pushing new technologies to generate improved measurements, 2) performing scaled-down experiments wherever possible, and finally 3) formulating computational/theoretical models that explain and predict details of the phenomenon.

In the case of active sensing, new technologies promise to lower the barrier for entry into acoustic tracking. In this thesis itself [Chapter \@ref(sfscotdoa)], we see the larval form of a field-friendly  workflow for mic position self-calibration. In its more developed form, this workflow will closely mirror current camera array calibration workflows (eg. @Theriault2014). The bioacoustician only needs to arrive at the field site, setup the microphones unobtrusively in the recording volume. To later infer the microphone positions, playbacks with a small speaker may be necessary (the animal vocalisations could themselves be used instead!). Multi-channel microphone arrays are of course typically associated with reams of cables extruding from the soundcard leading to the microphones. Cables need constant maintenance, and can in my experience, contribute to a considerable portion of weight during field work. In the future, I see the scope for either wireless multi-channel recording systems, or more strategically, the potential for acoustic tracking with many independently recording devices. Acoustic tracking needs accurate time-difference of arrivals, and this has always been done so far using multi-channel soundcards that digitise data synchronously for all channels. In principle however, time-difference-of-arrivals may also be measured across two unsynchronised channels as long as the temporal offset between them is known. Similar to microphone position self-calibration, recent methods to estimate offset between asynchronous channels post-hoc  [@burgess2012node;@burgess2013minimal] promise the next methodological advance to the bioacoustician in the field. Acoustic tracking may then be done with with many smaller, cheaper and more portable recording devices. A future workflow may even include placing hundreds to thousands of hand-held recorders in a cave, recording data, and then finally performing playbacks for cross-device synchronisation and position calibration. Groups of bats necessarily mean more complexity in the analysis of the associated data. Computer vision algorithms have made great strides into animal movement tracking, and software to reliably track hundreds to thousands of individuals is in place. On the other hand, there is much opportunity for methodological developments in the analysis complex audio data with overlapping sounds and match the same calls across multiple channels.

I use the term 'scaled-down' experiment to mean any attempt at estimating animal capabilities under relatively controlled conditions. As described in \@ref(parametrising), many aspects of the hearing capabilities of bats and other animals remain unknown. My own experience with parametrising the computational model in Chapter @cpnchapter has shown me the value of comparable experimental protocols, and even more, of multi-species studies with the same protocol. The psychophysics of only a handful of temperate and tropical bat species (*E. fuscus*,*P.pipistrellus*,*P.discolor*, *M. lyra*) have been characterised, despite the high speciosity of bats. In flightroom studies too, a uniform protocol across species will allow for direct comparisons of results. Continued exploration of the latest animal-tracking techniques with growing group sizes in flightrooms will provide a performance benchmark of the available techniques. The behavioural responses observed in flightrooms may then form the focus of field observations of much larger groups.

With inverse problems, modelling provides us a way to explore the feasibility of the proposed mechanism, and "revise our thinking about the processes occuring" [@otto2011biologist]. Despite the constant focus on sensory systems in this thesis, it is important to remember that active sensing animals are not merely 'sensors'. Echolocating bats are living, breathing animals that perform rapid, well co-ordinated *behaviours* using the sensory inputs they receive. Bats exhibit a host of fascinating behaviours using echolocation, including catching prey, fly long distances, care for their young, among which group flight is perhaps the most tantalising to piece-together conceptually. The bystander bioacoustician watching a  mating swarm of a few hundred bats flying in a cave is only occupied by the many reasons this shouldn't even be possible in the first place!  How can collective behaviours like swarming or cave emergence occur, despite the limited sensory inputs individuals receive about their neighour positions? For that matter, given the sophistication of bat echolocation in experimental noise, does an individual bat actually even perceive a drop in sensory input rate? Models of group echolocation [eg. Chapter \@ref(cpnchapter),@TOCOMPLETE-mazaryovel] rely on the input data used to parametrise them, which are often scarce. Even existing models when parametrised with new data may reveal a much more nuanced picture. Modelling may reveal that echo detection in groups occurs well, but the sensory challenge is attentional [@lemasson2009], ie. to choose the most relevant one in the shortest possible time to avoid collision. Even if bats are capable of tracking the positions of all of their neighbours in a group, may be they only respond to the closest one - much like the collision-avoidance heuristic shown in @vanderelst2015sensorimotor. 

The three-pronged approach advocated above is of course no task for a single investigator working all alone. The approach involves a dedicated back-and-forth between disciplinary ideas, methods and people. It is my hope to have provided a cursory glimpse in this thesis of the contributions it can bring. How active sensing animals aggregate and perform impressive feats is an exciting problem that has occupied and will continue occupied many of us in the years to come. Unphased by their own abilities, the bats, they carry on effortlessly milling around an invisible centre in pitch-black caves and emerging in smoke-like streams in the light of the setting sun.





