# Acknowledgements

*"There was a bat bat bat bat bat bat bat bat bat bat bat,
\newline
There was a wizard wizard wizard wizard wizard wizard wizard wizard wizard,
\newline 
There was a guy guy guy guy guy guy guy guy guy guy guy,
\newline
They worked by a lake with many swans
\newline
Studying bats from dusk to dawn...."*

	- *There was a bat bat bat bat bat bat bat bat bat bat bat*, a song-poem I recited at the Science Slam, 2019 MPIO Open Doors Science day.

And what a journey it has been, this Phd'fying for the past five plus years. Sitting in front of the screen with a few notes, I never really realised how much I've relied on all the amazing people around me to make it this far. Let's begin, starting from the office outwards in an ever growing radius from where I sit right now.

To my office-mates: Daniel who taught me the value of a nice silent office and the joy of handling bats, Theresa - your willingness to help and chat about all things science and random, and for introducing me to Kaeptn Peng. Danke Danke. To all other former and current AFEG and associated members down the corridor (Aiqing, Erin, Klemen, Lena, Leo, Stefan, Laura, Toni, Neetash, Verena + both Claires) thank you all for forming a great and supportive and enthu environment to come to work every day. A big shout-out to Toni for making the whole 2018 field season possible at all! Holger, it has been awesome working with you - and I owe you for teaching me the value of good presentation and rigour in science!

Haus 11, the out-house where all the cool people are, here's to all of you current and former Haus 11'ers for the random corridor conversations and barbecue evenings! Without the Hermes/Narada/Loki messenger-like figures (who roam across many worlds and are bearers of all kinds of knowledge) Nicole Drenkard and Diana Werner , many things would not have been possible logistically and administratively - here's a big thanks to both of you. Joerg at the Pfore : quatsch'ing with you has always been a joy every time I came to pick up chocolate or a parcel. The Max-Planck Institute for Ornithology, my place of work, I thank for having the best work-place conditions (and location) and support systems I have ever experienced. I always looked forward to arriving at work. From the people around the instit now to all things and beings around: the peaceful snow outside my window, the lake, the beautiful cycle-path to the institute, and the occasional deer eating away peacefully - I am in some way thankful to these experiences and many more that have directly or indirectly come to this point in time and space.

To my more distantly located colleagues in my graduate school, the IMPRS for Organismal Biology and all of you at the Ghetto - I thank you all for forming a supportive net to share the joy and vent the frustrations of a life in science. Special thanks to the grad school coordinators Maeggi Hieber-Ruiz, Fransisca Rosa Mende and Corinna Loes for readily providing support whenever asked for. 

Neetash, for simultaneously playing the multiple roles of colleague, friend and wife over the past few years - I can not say enough, and perhaps words will not do justice! I can only be thankful that you have been by my side through the ups and downs as I tried to phd my way through to this point. Reni, for providing an oasis to retreat from work while Qwirkl-ing away, and Dieter for being the amazing conversationalist and story-teller he is. 

My extended family in Germany: Apurva-Sindhu, Deepu-Ravi. My gratitude to you for creating a home away from home and a second base-camp over the past many years with their hospitality, food and love! Parts of this thesis literally wouldn't be written without all encouragement that came from giving me the space and time to write away in your homes along with all spiritual nourishment from the hot cups of chai and bonda-bajji's that came with it.

Amma-Appa, for constantly supporting all my weird ideas of becoming, at various points, a vet and/or a 'zoologist' (even before I actually knew what the word meant), etc! Praj - for being my go-to person in times of joy and confusion for work and life related matters. I am here only because of the unquestioning 'I-have-your-back' attitude you all have shown at each decision point that has come till now. 

And finally, I would not be here without all the bats flying through the night and in the caves far far away in Bulgaria. All the bats that hung around as I fumbled with cables with numb hands on cold autumn nights, as I learnt to patiently deal with (hundreds of?) metres of tangled cable every night, and set up equipment hoping they'd land up. When they did it was always a pleasure to watch and hear them. So here's to all you hovercraft Daubis, hyper pipistrelles and gliding Mouse-eared bats, none of this would have been possible without all of you - and this is looking to spend more years to come understanding you weird creatures! 

To everyone and everything mentioned above, and especially to all those who I have not mentioned - I convey my gratitude: thank you, danke, blagodarya, danke, dhanyavaadaa. _/\_ 
