--- 
title: "Theoretical and empirical investigation of echolocation in bat groups"
author: "Thejasvi Beleyur"
date: "$`r Sys.Date()`$"
site: bookdown::bookdown_site
documentclass: book
bibliography: ["beleyur-goerlitz-2020-refs.bib", "tacost-references.bib","cotdoa-filtered.bib","intro-discussion-refs.bib","itsfm-references.bib"]
biblio-style: apalike
link-citations: true
description: "A thesis" 
output:
  bookdown::pdf_book:
    latex_engine: lualatex
    includes:
      in_header: preamble.tex
always_allow_html: true
---

# Summary {-#summary}
English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English 

English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English 

English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English 
English  English English English English English English English English English 

English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English English  English English English English English English English English English 

\newpage

# Zusammenfassung {-#zusammenf}

Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch DeutschDeutsch Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch DeutschDeutschDeutsch Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch DeutschDeutschDeutsch Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch DeutschDeutschDeutsch Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch DeutschDeutschDeutsch Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch DeutschDeutschDeutsch Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch DeutschDeutschDeutsch Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch DeutschDeutschDeutsch Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch DeutschDeutschDeutsch Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch DeutschDeutschDeutsch Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch DeutschDeutschDeutsch Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch DeutschDeutschDeutsch Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch DeutschDeutschDeutsch Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch DeutschDeutschDeutsch Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch DeutschDeutschDeutsch Deutsch Deutsch Deutsch Deutsch Deutsch Deutsch DeutschDeutsch

\newpage 
 \
 \
 \
 \
 \
 \

*Bulla! I know not who I am,*

*Bulla! I know not who I am*

...

*Nor am I the believer in the mosque,*

*Nor am I in the rituals of the infidel,*

*Nor am I the pure in the impure,*

*Nor am I inherent in the Vedas*

...

*Nor am I of the water nor of the land,*

*Nor am I fire nor air,*

*Bulla! I know not who I am,*

*Nor am I Arabic nor from Lahore,*

...

*Nor did I name myself,*

*Beginning or end I know just the self,*

*Do not acknowledge duality,*

*There's none wiser than I*\



*Who is this Bulla Shah?*\

*Bulla! I know not who I am,*

*Bulla! I know not who I am*

 - Bulla Shah, Sufi mystic and poet ^[I interpret this poem as an apt expression of the simultaneous pleasure, confusion and contentment gained from inter-disciplinary research]. Translation by @bullashahtransl.

*Echolocation is still a topic that resists neat classification into any conventional category of science. It ramifies into widely different scientific disciplines including ethology, mammalogy, physiology, psychology, acoustics, nd the mathematical theory of signal detectionl. The results of new investigations have reemphasized the necessity of a broad biological perspective for any serious appreciation of echolocation.*

 - Donald Griffin, Listening in the Dark

\newpage

* Group living adds to
# General Introduction 
Animal sensory systems and behaviours evolve in response to a host of selection pressures such as predators, food and the environment [@EndlerREF]. Moths with ultrasonic hearing are able to evade echolocating bats, that have in turn developed echolocation strategies that evade moth hearing [@REFS]. The physical environment (eg. light, heat, humidity) also plays a strong role in selecting sensory systems. Cave fish inhabiting dark cave systems repeatedly evolve a loss of vision [@jeffery2001cavefish], while ABCDEFGHIJKLMON. The social environment, consisting of other conspecifics and interactions with them, is also of great importance in the life-cycle of most sexually reproducing animals. Even classically solitary animals such as tigers and spiders will (or seek to) encounter mates over the course of their life time. Sexual selection moulds behaviours and sensory systems as seen in territorial displays and female sensory drives in a wide variety of taxa [@REF] as epitomised by the dance and colourful patterns of the male peacock spider [@REF]. 

The social environment of animals in long-term social groups (eusocial insects and mammals) or short-term groups (eg. lekks, maternal colonies) is particularly filled with a continuous stream of multi-modal stimuli and presents a host of challenges that individual sensory systems and behaviours have evolved with. 

Group formation in animals (temporary or long-term,) has evolved multiple times across the animal kingdom. Individuals living in groups reap the benefits of this strategy, while also suffering its disadvantages [@Krebs??]. Animals in groups experience improved foraging, predator evasion, offspring survivals, to name a few advantages. However, the disadvantages also include, among others, increased resource competition among individuals and spread of disease [@Krebs??]. Group living animals also often show special adaptations for group-living itself, in terms of their morphology (eg. soldier, worker and alate ants, deer antlers []), behaviour (swarming and schooling in birds, mammals and fish []) and communication strategies (alarm calls in meerkats and marmots, human speech []) - all of which are a result of the challenges of group-living or . 

The fluidity with which individuals in a murmuration of starlings or school of fish move belie rapid and complex underlying sensorimotor loops behind such group events. These collective behaviours can be replicated in computational agent-based models with simple behavioural heuristics based on the relative proximity and position of each agent's neighbours [@reynolds1987a;@couzin2002a]. The 'sensorimotor loop' or behavioural heuristics in these models mimics what animals in a group are likely to be doing [@herbert2016understanding], and broadly consists of the following cycle: 1) the individual assessing the relative position and movement direction of its neighbours, 2) using a decision criterion to integrate information on the neighbour positions and movements and 3) moving in a direction using the integrated information. 

A key step in the initiation and maintenance of any collective behaviour is neighbour detection through the sensory modalities available to the animal. Many of the collective movements studied experimentally to date have been in visually dominant animals [@pita2016collective] such as birds, fish schools, mammals and flies. Vision is a passive sensory modality, in that the animal is merely a 'receiver' of light. The fact that each animal acts as a receiver, and does not affect the amount of light received by others majorly (eg. light obstruction due their body opacity) means that visually driven collective behaviour can scale well with group size. Given sufficient ambient light, individuals in all sizes of groups (small to large) are expected to independently be able to detect their neighbour's and thus show co-ordinated movement. This expectation is supported by experimental observations of thousand strong starling flocks [@ballerini2008a], schools with ten-hundreds of fish [@tunstrom2013collective], or even humans as we aggregate in small to very large groups [@moussaid2011simple;@dyer2009leadership]. Concrete support for the use of visual cues, and their role in modulating individual decisions in group movement is provided by studies that reconstruct individual sensory *umwelts* [@turner2002encoding;@strandburg2013visual;@belden2019vision]. In contrast to simple models that assume all neighbours in a fixed sensory volume can be detected [@reynolds1987a;@couzin2002a], sensory reconstruction approaches include the details of neighbour positions and visual acuity [@strandburg2013visual;@belden2019vision], and thus allow a detailed analysis of individual sensory inputs and motor outputs. What about collective motion driven by other sensory modalities where sensing is not independent and is actually expected to be impeded in larger groups?

## The 'noise' in active sensing groups  



## Bat echolocation 

### Listening in the chorus: from humans to animals 
Particularly from a sensory perspective, being part of a group brings about its own set of challenges. 
Animals have to deal with the task of sorting out noise from signal all the time - bird choruses [species can be trained to dteect single species in a chorus], frogs [Bee], cricket chorusses[Balakrishinan], and finally even humans. 

The psychoacoustic techniques and approaches used in humans have served a strong basis for many investigations in the field of animal acoustics/communication [BeeMicheyl2008]. eg. spatial unmasking, detecting signals at 'negative SNRs' and acoustic streaming have all been shown in animals in fact.  Many of the behaviourally relevant animal contexts studied to date have been in behaviours that the animal perhaps has a period of a few seconds or minutes to execute. The long time scale perhaps allows the individual to 'process' and consider the most relevant signal in the midst of the incoming cacophony. What happens however, when the process of signal 

* There are all kinds of adaptations in the animal kingdom. 
* Training/experience is known to improve performance

### Active sensing animals and listening in the noise
1. Active sensing animals emit energy and blah blah blah.
1. Discerning the correct type of signal from the bakcground is important but most of these other animals use the cues for decisions that are made over somewhat longer time scales eg. a few seconds to a few minutes. 

1. But active sensing animals need to manage in the *now*, and show a variety of adaptations in response. Electric fish, dolphins, bats. eg. JAR in electric fish, calling louder in bats, dolphins etc. The rapidness of the adaptation indicates how vital it is for the animals??

### Active sensing in bats and in noise
1. Echolocating bats emit loud calls and listen for echoes --
1. The returning echoes serve as packets of information that the bat uses to gain insights about its surroundings. The time delay, echo level, interference and spectral properties and other blah blah tell the bat more about the objects. 
1. Echolocation might work based on a type of efference copy based mechanism. 
1. 

### Sensory adaptations for listening in the 'noise'
* Spatial unmasking
* 

### 

### Treading trodden paths with new technology 
How the study of group echolocation has always fascinated scientists but the technology (hardware and software) has not always been very accesible till now. Now is a GoldenZeit. 

### Focus on open and reproducible science 
Uploading all my data, documenting code and publishing code as packages with publicly available tutorials are part of my attempts to share the science I do as much as possible. 

### Group echolocation as a 'serious' sensory challenge

### Implications of group echolocation on collective behaviour 

1. Analogies to RADAR: one might think a negative signal-to-noise ratio is not possible. But published data clearly shows this - and also, that when there is a

## Thesis outline 
In this thesis I will investigate the sensory  challenge faced by active sensing animals using a combination of experimental and theoretical methods. Through modelling I will reveal and quantify the sensory challenge FM echolocating bats face in groups of various sizes. I will then present the results of an observational study detailing the echolocation strategies of CF-FM bats in the presence of conspecifics, followed by a novel experimental dataset and workflow to study groups of echolocating bats in the wild. I will end with a series of methodologically driven reports that will significantly reduce the effort needed to perform acoustic tracking, help users simulate the expected performance of their arrays and ease the computational reproduciblity of echolocation call analysis. 

```{r echo=FALSE}
#CPN chapter
```
Echolocation is expected to become increasingly infeasible with growing group sizes due to masking. In response to masking in the form of artificial playbacks and conspecific calls, bats show a variety of changes to their echolocation behaviour. While many experimental studies have reported the changes bats show as 'emitters' of sound, very little focus had been given to date on bats as 'receivers'. Computational work modelling group echolocation has been restricted to models that are qualitatively by the biology of echolocation.  In chapter \@ref(cpnchapter) I present an experimentally parameterised computational model that estimates the sensory inputs a bat may receive in terms of the number of echoes detected over a range of group sizes. I formulated a conceptual framework to estimate echo detection in the presence of noise by combining published literature on the bat auditory system and echolocation.

In Chapter 3 (Horseshoebat), I present bow bow bow . A little bit about CF bats, and how they are more likely to face overlaps than FM bats at least temporally. 

In Chapter 4 (Uschichka), I do kat kat kat kat. From the time of Griffin & Galambos, who were the first to use the newly invented ultrasonic microphone to record ultrasound calls - the field of echolocation has always been a field that has 'resisted '

In Chapter 5 (SFS), 
1. About the SFS methodology : Multi-microphone arrays have been an important and indispensable tool in the study of echolocation in the laboratory ever since the work of  [Aubauer XXXX]. Working with microphone arrays in the field however comes with a series of challenges. Handling multi-microphone arrays in the field can be logistically and physically straining: the long cables involved must be brought to order each time, the arrays themselves can be bulky and must be assembled on site each time, and in certain configurations the positions of each microphone may need to be measured each time the array is setup. While rewarding in terms of the data it generates, the process of setting up a microphone array can be strenuous especially when it comes to taking positional measurements of microphone positions. The use of TotalStation type surveying systems that provide direct XYZ measurements are not common in the field (they are themselves another piece of bulky equipment), and instead it is more common to measure inter-microphone distances with a tape measure or laser range finders. Having measured the inter-microphone distances in an array, the final XYZ positions of each microphone can be reconstructed. In my search for a method that .......an academic 'Christmas present'. 

In Chapter 6 (tacost), 

In Chapter 7 (itsfm)


